name: Build and Deploy to Local Minikube

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted  # This specifies that the job runs on your local machine

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t manigowtham08/Poll-app:latest .
        docker push manigowtham08/Poll-app:latest

    - name: Deploy to Minikube
      run: |
        # Load the Docker image into Minikube
        minikube image load manigowtham08/Poll-app:latest
        
        # Apply Kubernetes configurations
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
